// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewAIProviderPort creates a new instance of AIProviderPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAIProviderPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *AIProviderPort {
	mock := &AIProviderPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AIProviderPort is an autogenerated mock type for the AIProviderPort type
type AIProviderPort struct {
	mock.Mock
}

type AIProviderPort_Expecter struct {
	mock *mock.Mock
}

func (_m *AIProviderPort) EXPECT() *AIProviderPort_Expecter {
	return &AIProviderPort_Expecter{mock: &_m.Mock}
}

// ReviewCode provides a mock function for the type AIProviderPort
func (_mock *AIProviderPort) ReviewCode(diff string) (string, error) {
	ret := _mock.Called(diff)

	if len(ret) == 0 {
		panic("no return value specified for ReviewCode")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(diff)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(diff)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(diff)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AIProviderPort_ReviewCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReviewCode'
type AIProviderPort_ReviewCode_Call struct {
	*mock.Call
}

// ReviewCode is a helper method to define mock.On call
//   - diff string
func (_e *AIProviderPort_Expecter) ReviewCode(diff interface{}) *AIProviderPort_ReviewCode_Call {
	return &AIProviderPort_ReviewCode_Call{Call: _e.mock.On("ReviewCode", diff)}
}

func (_c *AIProviderPort_ReviewCode_Call) Run(run func(diff string)) *AIProviderPort_ReviewCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AIProviderPort_ReviewCode_Call) Return(s string, err error) *AIProviderPort_ReviewCode_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *AIProviderPort_ReviewCode_Call) RunAndReturn(run func(diff string) (string, error)) *AIProviderPort_ReviewCode_Call {
	_c.Call.Return(run)
	return _c
}
