// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewConfigPort creates a new instance of ConfigPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigPort {
	mock := &ConfigPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ConfigPort is an autogenerated mock type for the ConfigPort type
type ConfigPort struct {
	mock.Mock
}

type ConfigPort_Expecter struct {
	mock *mock.Mock
}

func (_m *ConfigPort) EXPECT() *ConfigPort_Expecter {
	return &ConfigPort_Expecter{mock: &_m.Mock}
}

// GetAIProvider provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetAIProvider() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAIProvider")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetAIProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAIProvider'
type ConfigPort_GetAIProvider_Call struct {
	*mock.Call
}

// GetAIProvider is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetAIProvider() *ConfigPort_GetAIProvider_Call {
	return &ConfigPort_GetAIProvider_Call{Call: _e.mock.On("GetAIProvider")}
}

func (_c *ConfigPort_GetAIProvider_Call) Run(run func()) *ConfigPort_GetAIProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetAIProvider_Call) Return(s string) *ConfigPort_GetAIProvider_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetAIProvider_Call) RunAndReturn(run func() string) *ConfigPort_GetAIProvider_Call {
	_c.Call.Return(run)
	return _c
}

// GetAnthropicAuthToken provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetAnthropicAuthToken() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAnthropicAuthToken")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetAnthropicAuthToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnthropicAuthToken'
type ConfigPort_GetAnthropicAuthToken_Call struct {
	*mock.Call
}

// GetAnthropicAuthToken is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetAnthropicAuthToken() *ConfigPort_GetAnthropicAuthToken_Call {
	return &ConfigPort_GetAnthropicAuthToken_Call{Call: _e.mock.On("GetAnthropicAuthToken")}
}

func (_c *ConfigPort_GetAnthropicAuthToken_Call) Run(run func()) *ConfigPort_GetAnthropicAuthToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetAnthropicAuthToken_Call) Return(s string) *ConfigPort_GetAnthropicAuthToken_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetAnthropicAuthToken_Call) RunAndReturn(run func() string) *ConfigPort_GetAnthropicAuthToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetAnthropicBaseURL provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetAnthropicBaseURL() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAnthropicBaseURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetAnthropicBaseURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnthropicBaseURL'
type ConfigPort_GetAnthropicBaseURL_Call struct {
	*mock.Call
}

// GetAnthropicBaseURL is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetAnthropicBaseURL() *ConfigPort_GetAnthropicBaseURL_Call {
	return &ConfigPort_GetAnthropicBaseURL_Call{Call: _e.mock.On("GetAnthropicBaseURL")}
}

func (_c *ConfigPort_GetAnthropicBaseURL_Call) Run(run func()) *ConfigPort_GetAnthropicBaseURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetAnthropicBaseURL_Call) Return(s string) *ConfigPort_GetAnthropicBaseURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetAnthropicBaseURL_Call) RunAndReturn(run func() string) *ConfigPort_GetAnthropicBaseURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetAnthropicModel provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetAnthropicModel() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAnthropicModel")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetAnthropicModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnthropicModel'
type ConfigPort_GetAnthropicModel_Call struct {
	*mock.Call
}

// GetAnthropicModel is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetAnthropicModel() *ConfigPort_GetAnthropicModel_Call {
	return &ConfigPort_GetAnthropicModel_Call{Call: _e.mock.On("GetAnthropicModel")}
}

func (_c *ConfigPort_GetAnthropicModel_Call) Run(run func()) *ConfigPort_GetAnthropicModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetAnthropicModel_Call) Return(s string) *ConfigPort_GetAnthropicModel_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetAnthropicModel_Call) RunAndReturn(run func() string) *ConfigPort_GetAnthropicModel_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentPrefix provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetCommentPrefix() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCommentPrefix")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetCommentPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentPrefix'
type ConfigPort_GetCommentPrefix_Call struct {
	*mock.Call
}

// GetCommentPrefix is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetCommentPrefix() *ConfigPort_GetCommentPrefix_Call {
	return &ConfigPort_GetCommentPrefix_Call{Call: _e.mock.On("GetCommentPrefix")}
}

func (_c *ConfigPort_GetCommentPrefix_Call) Run(run func()) *ConfigPort_GetCommentPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetCommentPrefix_Call) Return(s string) *ConfigPort_GetCommentPrefix_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetCommentPrefix_Call) RunAndReturn(run func() string) *ConfigPort_GetCommentPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommitSHA provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetCommitSHA() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCommitSHA")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetCommitSHA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommitSHA'
type ConfigPort_GetCommitSHA_Call struct {
	*mock.Call
}

// GetCommitSHA is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetCommitSHA() *ConfigPort_GetCommitSHA_Call {
	return &ConfigPort_GetCommitSHA_Call{Call: _e.mock.On("GetCommitSHA")}
}

func (_c *ConfigPort_GetCommitSHA_Call) Run(run func()) *ConfigPort_GetCommitSHA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetCommitSHA_Call) Return(s string) *ConfigPort_GetCommitSHA_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetCommitSHA_Call) RunAndReturn(run func() string) *ConfigPort_GetCommitSHA_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeleteBotComments provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetDeleteBotComments() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDeleteBotComments")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ConfigPort_GetDeleteBotComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeleteBotComments'
type ConfigPort_GetDeleteBotComments_Call struct {
	*mock.Call
}

// GetDeleteBotComments is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetDeleteBotComments() *ConfigPort_GetDeleteBotComments_Call {
	return &ConfigPort_GetDeleteBotComments_Call{Call: _e.mock.On("GetDeleteBotComments")}
}

func (_c *ConfigPort_GetDeleteBotComments_Call) Run(run func()) *ConfigPort_GetDeleteBotComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetDeleteBotComments_Call) Return(b bool) *ConfigPort_GetDeleteBotComments_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ConfigPort_GetDeleteBotComments_Call) RunAndReturn(run func() bool) *ConfigPort_GetDeleteBotComments_Call {
	_c.Call.Return(run)
	return _c
}

// GetGitHubOwner provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetGitHubOwner() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGitHubOwner")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetGitHubOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGitHubOwner'
type ConfigPort_GetGitHubOwner_Call struct {
	*mock.Call
}

// GetGitHubOwner is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetGitHubOwner() *ConfigPort_GetGitHubOwner_Call {
	return &ConfigPort_GetGitHubOwner_Call{Call: _e.mock.On("GetGitHubOwner")}
}

func (_c *ConfigPort_GetGitHubOwner_Call) Run(run func()) *ConfigPort_GetGitHubOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetGitHubOwner_Call) Return(s string) *ConfigPort_GetGitHubOwner_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetGitHubOwner_Call) RunAndReturn(run func() string) *ConfigPort_GetGitHubOwner_Call {
	_c.Call.Return(run)
	return _c
}

// GetGitHubPRNumber provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetGitHubPRNumber() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGitHubPRNumber")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetGitHubPRNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGitHubPRNumber'
type ConfigPort_GetGitHubPRNumber_Call struct {
	*mock.Call
}

// GetGitHubPRNumber is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetGitHubPRNumber() *ConfigPort_GetGitHubPRNumber_Call {
	return &ConfigPort_GetGitHubPRNumber_Call{Call: _e.mock.On("GetGitHubPRNumber")}
}

func (_c *ConfigPort_GetGitHubPRNumber_Call) Run(run func()) *ConfigPort_GetGitHubPRNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetGitHubPRNumber_Call) Return(s string) *ConfigPort_GetGitHubPRNumber_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetGitHubPRNumber_Call) RunAndReturn(run func() string) *ConfigPort_GetGitHubPRNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetGitHubRepo provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetGitHubRepo() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGitHubRepo")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetGitHubRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGitHubRepo'
type ConfigPort_GetGitHubRepo_Call struct {
	*mock.Call
}

// GetGitHubRepo is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetGitHubRepo() *ConfigPort_GetGitHubRepo_Call {
	return &ConfigPort_GetGitHubRepo_Call{Call: _e.mock.On("GetGitHubRepo")}
}

func (_c *ConfigPort_GetGitHubRepo_Call) Run(run func()) *ConfigPort_GetGitHubRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetGitHubRepo_Call) Return(s string) *ConfigPort_GetGitHubRepo_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetGitHubRepo_Call) RunAndReturn(run func() string) *ConfigPort_GetGitHubRepo_Call {
	_c.Call.Return(run)
	return _c
}

// GetGitHubToken provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetGitHubToken() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGitHubToken")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetGitHubToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGitHubToken'
type ConfigPort_GetGitHubToken_Call struct {
	*mock.Call
}

// GetGitHubToken is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetGitHubToken() *ConfigPort_GetGitHubToken_Call {
	return &ConfigPort_GetGitHubToken_Call{Call: _e.mock.On("GetGitHubToken")}
}

func (_c *ConfigPort_GetGitHubToken_Call) Run(run func()) *ConfigPort_GetGitHubToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetGitHubToken_Call) Return(s string) *ConfigPort_GetGitHubToken_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetGitHubToken_Call) RunAndReturn(run func() string) *ConfigPort_GetGitHubToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetGitLabToken provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetGitLabToken() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGitLabToken")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetGitLabToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGitLabToken'
type ConfigPort_GetGitLabToken_Call struct {
	*mock.Call
}

// GetGitLabToken is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetGitLabToken() *ConfigPort_GetGitLabToken_Call {
	return &ConfigPort_GetGitLabToken_Call{Call: _e.mock.On("GetGitLabToken")}
}

func (_c *ConfigPort_GetGitLabToken_Call) Run(run func()) *ConfigPort_GetGitLabToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetGitLabToken_Call) Return(s string) *ConfigPort_GetGitLabToken_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetGitLabToken_Call) RunAndReturn(run func() string) *ConfigPort_GetGitLabToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetGitLabURL provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetGitLabURL() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGitLabURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetGitLabURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGitLabURL'
type ConfigPort_GetGitLabURL_Call struct {
	*mock.Call
}

// GetGitLabURL is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetGitLabURL() *ConfigPort_GetGitLabURL_Call {
	return &ConfigPort_GetGitLabURL_Call{Call: _e.mock.On("GetGitLabURL")}
}

func (_c *ConfigPort_GetGitLabURL_Call) Run(run func()) *ConfigPort_GetGitLabURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetGitLabURL_Call) Return(s string) *ConfigPort_GetGitLabURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetGitLabURL_Call) RunAndReturn(run func() string) *ConfigPort_GetGitLabURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetMergeRequestDiffBaseSHA provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetMergeRequestDiffBaseSHA() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMergeRequestDiffBaseSHA")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetMergeRequestDiffBaseSHA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMergeRequestDiffBaseSHA'
type ConfigPort_GetMergeRequestDiffBaseSHA_Call struct {
	*mock.Call
}

// GetMergeRequestDiffBaseSHA is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetMergeRequestDiffBaseSHA() *ConfigPort_GetMergeRequestDiffBaseSHA_Call {
	return &ConfigPort_GetMergeRequestDiffBaseSHA_Call{Call: _e.mock.On("GetMergeRequestDiffBaseSHA")}
}

func (_c *ConfigPort_GetMergeRequestDiffBaseSHA_Call) Run(run func()) *ConfigPort_GetMergeRequestDiffBaseSHA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetMergeRequestDiffBaseSHA_Call) Return(s string) *ConfigPort_GetMergeRequestDiffBaseSHA_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetMergeRequestDiffBaseSHA_Call) RunAndReturn(run func() string) *ConfigPort_GetMergeRequestDiffBaseSHA_Call {
	_c.Call.Return(run)
	return _c
}

// GetMergeRequestIID provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetMergeRequestIID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMergeRequestIID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetMergeRequestIID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMergeRequestIID'
type ConfigPort_GetMergeRequestIID_Call struct {
	*mock.Call
}

// GetMergeRequestIID is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetMergeRequestIID() *ConfigPort_GetMergeRequestIID_Call {
	return &ConfigPort_GetMergeRequestIID_Call{Call: _e.mock.On("GetMergeRequestIID")}
}

func (_c *ConfigPort_GetMergeRequestIID_Call) Run(run func()) *ConfigPort_GetMergeRequestIID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetMergeRequestIID_Call) Return(s string) *ConfigPort_GetMergeRequestIID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetMergeRequestIID_Call) RunAndReturn(run func() string) *ConfigPort_GetMergeRequestIID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMiniMaxAPIKey provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetMiniMaxAPIKey() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMiniMaxAPIKey")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetMiniMaxAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMiniMaxAPIKey'
type ConfigPort_GetMiniMaxAPIKey_Call struct {
	*mock.Call
}

// GetMiniMaxAPIKey is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetMiniMaxAPIKey() *ConfigPort_GetMiniMaxAPIKey_Call {
	return &ConfigPort_GetMiniMaxAPIKey_Call{Call: _e.mock.On("GetMiniMaxAPIKey")}
}

func (_c *ConfigPort_GetMiniMaxAPIKey_Call) Run(run func()) *ConfigPort_GetMiniMaxAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetMiniMaxAPIKey_Call) Return(s string) *ConfigPort_GetMiniMaxAPIKey_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetMiniMaxAPIKey_Call) RunAndReturn(run func() string) *ConfigPort_GetMiniMaxAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetMiniMaxBaseURL provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetMiniMaxBaseURL() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMiniMaxBaseURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetMiniMaxBaseURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMiniMaxBaseURL'
type ConfigPort_GetMiniMaxBaseURL_Call struct {
	*mock.Call
}

// GetMiniMaxBaseURL is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetMiniMaxBaseURL() *ConfigPort_GetMiniMaxBaseURL_Call {
	return &ConfigPort_GetMiniMaxBaseURL_Call{Call: _e.mock.On("GetMiniMaxBaseURL")}
}

func (_c *ConfigPort_GetMiniMaxBaseURL_Call) Run(run func()) *ConfigPort_GetMiniMaxBaseURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetMiniMaxBaseURL_Call) Return(s string) *ConfigPort_GetMiniMaxBaseURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetMiniMaxBaseURL_Call) RunAndReturn(run func() string) *ConfigPort_GetMiniMaxBaseURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetMiniMaxModel provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetMiniMaxModel() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMiniMaxModel")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetMiniMaxModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMiniMaxModel'
type ConfigPort_GetMiniMaxModel_Call struct {
	*mock.Call
}

// GetMiniMaxModel is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetMiniMaxModel() *ConfigPort_GetMiniMaxModel_Call {
	return &ConfigPort_GetMiniMaxModel_Call{Call: _e.mock.On("GetMiniMaxModel")}
}

func (_c *ConfigPort_GetMiniMaxModel_Call) Run(run func()) *ConfigPort_GetMiniMaxModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetMiniMaxModel_Call) Return(s string) *ConfigPort_GetMiniMaxModel_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetMiniMaxModel_Call) RunAndReturn(run func() string) *ConfigPort_GetMiniMaxModel_Call {
	_c.Call.Return(run)
	return _c
}

// GetOllamaAPIKey provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetOllamaAPIKey() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOllamaAPIKey")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetOllamaAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOllamaAPIKey'
type ConfigPort_GetOllamaAPIKey_Call struct {
	*mock.Call
}

// GetOllamaAPIKey is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetOllamaAPIKey() *ConfigPort_GetOllamaAPIKey_Call {
	return &ConfigPort_GetOllamaAPIKey_Call{Call: _e.mock.On("GetOllamaAPIKey")}
}

func (_c *ConfigPort_GetOllamaAPIKey_Call) Run(run func()) *ConfigPort_GetOllamaAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetOllamaAPIKey_Call) Return(s string) *ConfigPort_GetOllamaAPIKey_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetOllamaAPIKey_Call) RunAndReturn(run func() string) *ConfigPort_GetOllamaAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetOllamaModel provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetOllamaModel() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOllamaModel")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetOllamaModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOllamaModel'
type ConfigPort_GetOllamaModel_Call struct {
	*mock.Call
}

// GetOllamaModel is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetOllamaModel() *ConfigPort_GetOllamaModel_Call {
	return &ConfigPort_GetOllamaModel_Call{Call: _e.mock.On("GetOllamaModel")}
}

func (_c *ConfigPort_GetOllamaModel_Call) Run(run func()) *ConfigPort_GetOllamaModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetOllamaModel_Call) Return(s string) *ConfigPort_GetOllamaModel_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetOllamaModel_Call) RunAndReturn(run func() string) *ConfigPort_GetOllamaModel_Call {
	_c.Call.Return(run)
	return _c
}

// GetOllamaURL provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetOllamaURL() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOllamaURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetOllamaURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOllamaURL'
type ConfigPort_GetOllamaURL_Call struct {
	*mock.Call
}

// GetOllamaURL is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetOllamaURL() *ConfigPort_GetOllamaURL_Call {
	return &ConfigPort_GetOllamaURL_Call{Call: _e.mock.On("GetOllamaURL")}
}

func (_c *ConfigPort_GetOllamaURL_Call) Run(run func()) *ConfigPort_GetOllamaURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetOllamaURL_Call) Return(s string) *ConfigPort_GetOllamaURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetOllamaURL_Call) RunAndReturn(run func() string) *ConfigPort_GetOllamaURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetOpenAIAPIKey provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetOpenAIAPIKey() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOpenAIAPIKey")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetOpenAIAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOpenAIAPIKey'
type ConfigPort_GetOpenAIAPIKey_Call struct {
	*mock.Call
}

// GetOpenAIAPIKey is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetOpenAIAPIKey() *ConfigPort_GetOpenAIAPIKey_Call {
	return &ConfigPort_GetOpenAIAPIKey_Call{Call: _e.mock.On("GetOpenAIAPIKey")}
}

func (_c *ConfigPort_GetOpenAIAPIKey_Call) Run(run func()) *ConfigPort_GetOpenAIAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetOpenAIAPIKey_Call) Return(s string) *ConfigPort_GetOpenAIAPIKey_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetOpenAIAPIKey_Call) RunAndReturn(run func() string) *ConfigPort_GetOpenAIAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetOpenAIBaseURL provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetOpenAIBaseURL() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOpenAIBaseURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetOpenAIBaseURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOpenAIBaseURL'
type ConfigPort_GetOpenAIBaseURL_Call struct {
	*mock.Call
}

// GetOpenAIBaseURL is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetOpenAIBaseURL() *ConfigPort_GetOpenAIBaseURL_Call {
	return &ConfigPort_GetOpenAIBaseURL_Call{Call: _e.mock.On("GetOpenAIBaseURL")}
}

func (_c *ConfigPort_GetOpenAIBaseURL_Call) Run(run func()) *ConfigPort_GetOpenAIBaseURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetOpenAIBaseURL_Call) Return(s string) *ConfigPort_GetOpenAIBaseURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetOpenAIBaseURL_Call) RunAndReturn(run func() string) *ConfigPort_GetOpenAIBaseURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetOpenAIModel provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetOpenAIModel() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOpenAIModel")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetOpenAIModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOpenAIModel'
type ConfigPort_GetOpenAIModel_Call struct {
	*mock.Call
}

// GetOpenAIModel is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetOpenAIModel() *ConfigPort_GetOpenAIModel_Call {
	return &ConfigPort_GetOpenAIModel_Call{Call: _e.mock.On("GetOpenAIModel")}
}

func (_c *ConfigPort_GetOpenAIModel_Call) Run(run func()) *ConfigPort_GetOpenAIModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetOpenAIModel_Call) Return(s string) *ConfigPort_GetOpenAIModel_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetOpenAIModel_Call) RunAndReturn(run func() string) *ConfigPort_GetOpenAIModel_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectID provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetProjectID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProjectID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetProjectID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectID'
type ConfigPort_GetProjectID_Call struct {
	*mock.Call
}

// GetProjectID is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetProjectID() *ConfigPort_GetProjectID_Call {
	return &ConfigPort_GetProjectID_Call{Call: _e.mock.On("GetProjectID")}
}

func (_c *ConfigPort_GetProjectID_Call) Run(run func()) *ConfigPort_GetProjectID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetProjectID_Call) Return(s string) *ConfigPort_GetProjectID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetProjectID_Call) RunAndReturn(run func() string) *ConfigPort_GetProjectID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRunTimeout provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetRunTimeout() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRunTimeout")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// ConfigPort_GetRunTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRunTimeout'
type ConfigPort_GetRunTimeout_Call struct {
	*mock.Call
}

// GetRunTimeout is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetRunTimeout() *ConfigPort_GetRunTimeout_Call {
	return &ConfigPort_GetRunTimeout_Call{Call: _e.mock.On("GetRunTimeout")}
}

func (_c *ConfigPort_GetRunTimeout_Call) Run(run func()) *ConfigPort_GetRunTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetRunTimeout_Call) Return(duration time.Duration) *ConfigPort_GetRunTimeout_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *ConfigPort_GetRunTimeout_Call) RunAndReturn(run func() time.Duration) *ConfigPort_GetRunTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// GetVCSProvider provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetVCSProvider() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVCSProvider")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ConfigPort_GetVCSProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVCSProvider'
type ConfigPort_GetVCSProvider_Call struct {
	*mock.Call
}

// GetVCSProvider is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetVCSProvider() *ConfigPort_GetVCSProvider_Call {
	return &ConfigPort_GetVCSProvider_Call{Call: _e.mock.On("GetVCSProvider")}
}

func (_c *ConfigPort_GetVCSProvider_Call) Run(run func()) *ConfigPort_GetVCSProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetVCSProvider_Call) Return(s string) *ConfigPort_GetVCSProvider_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ConfigPort_GetVCSProvider_Call) RunAndReturn(run func() string) *ConfigPort_GetVCSProvider_Call {
	_c.Call.Return(run)
	return _c
}
