// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/adlandh/ai-mr-reviewer/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMRProviderPort creates a new instance of MRProviderPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMRProviderPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MRProviderPort {
	mock := &MRProviderPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MRProviderPort is an autogenerated mock type for the MRProviderPort type
type MRProviderPort struct {
	mock.Mock
}

type MRProviderPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MRProviderPort) EXPECT() *MRProviderPort_Expecter {
	return &MRProviderPort_Expecter{mock: &_m.Mock}
}

// AddMergeRequestDiscussion provides a mock function for the type MRProviderPort
func (_mock *MRProviderPort) AddMergeRequestDiscussion(ctx context.Context, file string, line int, note string) error {
	ret := _mock.Called(ctx, file, line, note)

	if len(ret) == 0 {
		panic("no return value specified for AddMergeRequestDiscussion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, string) error); ok {
		r0 = returnFunc(ctx, file, line, note)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MRProviderPort_AddMergeRequestDiscussion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMergeRequestDiscussion'
type MRProviderPort_AddMergeRequestDiscussion_Call struct {
	*mock.Call
}

// AddMergeRequestDiscussion is a helper method to define mock.On call
//   - ctx context.Context
//   - file string
//   - line int
//   - note string
func (_e *MRProviderPort_Expecter) AddMergeRequestDiscussion(ctx interface{}, file interface{}, line interface{}, note interface{}) *MRProviderPort_AddMergeRequestDiscussion_Call {
	return &MRProviderPort_AddMergeRequestDiscussion_Call{Call: _e.mock.On("AddMergeRequestDiscussion", ctx, file, line, note)}
}

func (_c *MRProviderPort_AddMergeRequestDiscussion_Call) Run(run func(ctx context.Context, file string, line int, note string)) *MRProviderPort_AddMergeRequestDiscussion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MRProviderPort_AddMergeRequestDiscussion_Call) Return(err error) *MRProviderPort_AddMergeRequestDiscussion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MRProviderPort_AddMergeRequestDiscussion_Call) RunAndReturn(run func(ctx context.Context, file string, line int, note string) error) *MRProviderPort_AddMergeRequestDiscussion_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBotCommentsExceptResolved provides a mock function for the type MRProviderPort
func (_mock *MRProviderPort) DeleteBotCommentsExceptResolved(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBotCommentsExceptResolved")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MRProviderPort_DeleteBotCommentsExceptResolved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBotCommentsExceptResolved'
type MRProviderPort_DeleteBotCommentsExceptResolved_Call struct {
	*mock.Call
}

// DeleteBotCommentsExceptResolved is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MRProviderPort_Expecter) DeleteBotCommentsExceptResolved(ctx interface{}) *MRProviderPort_DeleteBotCommentsExceptResolved_Call {
	return &MRProviderPort_DeleteBotCommentsExceptResolved_Call{Call: _e.mock.On("DeleteBotCommentsExceptResolved", ctx)}
}

func (_c *MRProviderPort_DeleteBotCommentsExceptResolved_Call) Run(run func(ctx context.Context)) *MRProviderPort_DeleteBotCommentsExceptResolved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MRProviderPort_DeleteBotCommentsExceptResolved_Call) Return(err error) *MRProviderPort_DeleteBotCommentsExceptResolved_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MRProviderPort_DeleteBotCommentsExceptResolved_Call) RunAndReturn(run func(ctx context.Context) error) *MRProviderPort_DeleteBotCommentsExceptResolved_Call {
	_c.Call.Return(run)
	return _c
}

// GetExistingComments provides a mock function for the type MRProviderPort
func (_mock *MRProviderPort) GetExistingComments(ctx context.Context) (map[string][]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExistingComments")
	}

	var r0 map[string][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string][]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string][]string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MRProviderPort_GetExistingComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExistingComments'
type MRProviderPort_GetExistingComments_Call struct {
	*mock.Call
}

// GetExistingComments is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MRProviderPort_Expecter) GetExistingComments(ctx interface{}) *MRProviderPort_GetExistingComments_Call {
	return &MRProviderPort_GetExistingComments_Call{Call: _e.mock.On("GetExistingComments", ctx)}
}

func (_c *MRProviderPort_GetExistingComments_Call) Run(run func(ctx context.Context)) *MRProviderPort_GetExistingComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MRProviderPort_GetExistingComments_Call) Return(stringToStrings map[string][]string, err error) *MRProviderPort_GetExistingComments_Call {
	_c.Call.Return(stringToStrings, err)
	return _c
}

func (_c *MRProviderPort_GetExistingComments_Call) RunAndReturn(run func(ctx context.Context) (map[string][]string, error)) *MRProviderPort_GetExistingComments_Call {
	_c.Call.Return(run)
	return _c
}

// GetMergeRequestChanges provides a mock function for the type MRProviderPort
func (_mock *MRProviderPort) GetMergeRequestChanges(ctx context.Context) ([]domain.Diff, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMergeRequestChanges")
	}

	var r0 []domain.Diff
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Diff, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Diff); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Diff)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MRProviderPort_GetMergeRequestChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMergeRequestChanges'
type MRProviderPort_GetMergeRequestChanges_Call struct {
	*mock.Call
}

// GetMergeRequestChanges is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MRProviderPort_Expecter) GetMergeRequestChanges(ctx interface{}) *MRProviderPort_GetMergeRequestChanges_Call {
	return &MRProviderPort_GetMergeRequestChanges_Call{Call: _e.mock.On("GetMergeRequestChanges", ctx)}
}

func (_c *MRProviderPort_GetMergeRequestChanges_Call) Run(run func(ctx context.Context)) *MRProviderPort_GetMergeRequestChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MRProviderPort_GetMergeRequestChanges_Call) Return(diffs []domain.Diff, err error) *MRProviderPort_GetMergeRequestChanges_Call {
	_c.Call.Return(diffs, err)
	return _c
}

func (_c *MRProviderPort_GetMergeRequestChanges_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Diff, error)) *MRProviderPort_GetMergeRequestChanges_Call {
	_c.Call.Return(run)
	return _c
}
