pre-push:
  parallel: true
  commands:
    generate:
      tags: generate code
      run: go generate ./...
    lint:
      tags: run linter
      run: golangci-lint run
      glob: "*.go"
    test:
      tags: run tests
      run: go test -v -race ./...
      glob: "*.go"
